---
exp_name: "Dummy-50"
render: False
repetitions: 10
cem_stages: 1
episodes: 100
timesteps: 200
vel_burn_in_time: 100
pem_path: "models/det_baseline_full/pem_class_train_full"
safety_func: "classic"
